import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,Check,ChevronDown,ChevronRight,Clock3,FileText,ListTodo,LockKeyhole,Settings2,ShieldCheck,Square,Trash2,X,Brain,Download} from 'lucide-react';
import Companion from './Companion';
import AgentMessenger from './AgentMessenger';
import CharacterEditor from './CharacterEditor';
import {appearanceForTone,type CharacterAppearance} from '../../shared/character.mjs';
import AevoriSelect from './AevoriSelect';
import ChatMarkdown from './ChatMarkdown';
import './agent.css';
export type AgentArtifact={id:string;kind:'note'|'task';title:string;content:string;created:number};
type Action=AgentArtifact&{status:'pending'|'approved'|'rejected'|'blocked'};
type Run={mode?:'chat'|'work';id:string;goal:string;model:string;status:string;summary:string;steps:string[];actions:Action[];error?:string;created:number;events:{text:string;at:number}[];archived?:boolean};
export type AgentState={name:string;tone:string;appearance:CharacterAppearance;characterConfigured:boolean;memoryEnabled:boolean;memories:{id:string;kind:string;content:string}[];policy:{note:string;task:string};runs:Run[];artifacts:AgentArtifact[];messages:{id:string;role:'user'|'assistant';content:string;created:number;runId?:string;kind?:string}[];reminders:{id:string;text:string;at:number;deliveredAt?:number}[];readAt:number};
const statuses:Record<string,string>={running:'Arbeitet auf deinem Mac',review:'Wartet auf dich',done:'Gespeichert',reviewed:'Geprüft',stopped:'Angehalten',interrupted:'Unterbrochen',error:'Braucht einen neuen Versuch'};
export function useAgent(){
 const [state,setState]=useState<AgentState|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch('/api/agent/state');if(!r.ok)throw new Error('Dein Agent ist gerade nicht erreichbar.');const d=await r.json();if(alive){setState(d);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Nicht erreichbar.');}};void load();const t=setInterval(load,2500);return()=>{alive=false;clearInterval(t);};},[]);
 const action=async(path:string,body:unknown)=>{const r=await fetch('/api/agent/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Die Änderung konnte nicht gespeichert werden.');if(d.runs)setState(d);else if(path==='start')setState(current=>current?{...current,runs:[d,...current.runs.filter(run=>run.id!==d.id)]}:current);return d;};
 return {state,error,action};
}
type Props={agent:ReturnType<typeof useAgent>;onOpen:(view:'models'|'notes'|'tasks'|'team')=>void;onChat:()=>void;initialTab?:string};
export default function AgentWorkspace({agent,onOpen,onChat,initialTab='chat'}:Props){
 const characterButton=useRef<HTMLButtonElement>(null),characterLauncher=useRef<HTMLElement|null>(null);
 const openCharacter=()=>{characterLauncher.current=document.activeElement as HTMLElement;setEditing(true);};
 const [tab,setTab]=useState(initialTab),[goal,setGoal]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[kind,setKind]=useState('prefer'),[memory,setMemory]=useState(''),[showArchived,setShowArchived]=useState(false),[editing,setEditing]=useState(false),[characterSaved,setCharacterSaved]=useState(false);
 const state=agent.state,active=state?.runs.some(r=>r.status==='running'),pending=state?.runs.reduce((n,r)=>n+r.actions.filter(a=>a.status==='pending').length,0)||0;
 const act=async(path:string,body:unknown)=>{setError('');try{return await agent.action(path,body);}catch(e){setError(e instanceof Error?e.message:'Aktion fehlgeschlagen.');return null;}};
 if(!state)return <div className="agent-loading"><Companion active/><p role="status">{agent.error||'Dein Agent wird geöffnet …'}</p></div>;
 return <div className={`agent-space ${tab==='chat'?'messenger-space':''}`}>
  {tab!=='chat'&&<><div className="agent-top"><div className="agent-local"><span className="status-dot online"/>Auf deinem Mac</div><button ref={characterButton} className="character-create-button" onClick={()=>{setCharacterSaved(false);openCharacter();}}><Settings2 size={15}/>{state.characterConfigured?'Charakter bearbeiten':'Charakter erstellen'}</button></div>
  <header className={`agent-welcome ${state.runs.length?'compact':''}`}><Companion appearance={state.appearance} tone={state.tone} active={active} size={136}/><h1>{state.name}<span>Dein persönlicher Agent.</span></h1><p>{active?'Ich arbeite an deinem Auftrag.':pending?'Ein Ergebnis wartet auf deine Entscheidung.':'Was nehmen wir uns heute vor?'}</p></header>
  {!state.characterConfigured&&<section className="character-first-visit"><div><strong>Ein eigener Charakter für deinen Agenten.</strong><p>Wähle einen Namen, eine Form und die Details, die zu dir passen.</p></div><button className="primary" onClick={openCharacter}>Jetzt gestalten<ArrowUpRight size={15}/></button></section>}
  </>}{characterSaved&&<p className="character-saved" role="status"><Check size={14}/>Dein Charakter ist gespeichert.</p>}
  {editing&&<CharacterEditor name={state.name} appearance={state.appearance??appearanceForTone(state.tone)} configured={state.characterConfigured} onClose={()=>setEditing(false)} onReturnFocus={()=>(characterLauncher.current??characterButton.current)?.focus({preventScroll:true})} onSave={async draft=>{await agent.action('profile',draft);setCharacterSaved(true);}}/>}

  <nav className="agent-tabs" aria-label="Agent-Bereiche">{[['chat','Nachrichten'],['work','Aufträge'],['memory','Gedächtnis'],['rules','Regeln']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}{id==='work'&&pending>0&&<span>{pending}</span>}</button>)}</nav>
  {(error||agent.error)&&<div className="error-banner" role="alert">{error||agent.error}</div>}
  {tab==='chat'&&<AgentMessenger state={state} act={act} onCharacter={openCharacter} onWork={()=>setTab('work')}/> }
  {tab==='work'&&<>
   <form className="agent-brief" onSubmit={async e=>{e.preventDefault();if(!goal.trim())return;setSending(true);const d=await act('start',{goal});if(d)setGoal('');setSending(false);}}><label className="sr-only" htmlFor="agent-goal">Auftrag für deinen Agenten</label><textarea id="agent-goal" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={6000} rows={3} placeholder="Eine Idee, ein Ziel oder etwas, das erledigt werden soll …"/><div><span><LockKeyhole size={13}/>Lokale KI. Deine Regeln.</span><button className="agent-send" aria-label="Auftrag starten" disabled={sending||active||!goal.trim()}>{sending?<Clock3 size={19}/>:<ArrowUp size={20}/>}</button></div></form>
   {!state.runs.length&&<div className="agent-examples">{['Erstelle einen übersichtlichen Wochenplan mit drei Prioritäten.','Entwirf eine kurze Projektbeschreibung und die nächsten Aufgaben.'].map(t=><button key={t} onClick={()=>setGoal(t)}>{t}<ArrowUpRight size={15}/></button>)}</div>}
   <div className="agent-list-options"><button className="text-button" onClick={()=>setShowArchived(!showArchived)}>{showArchived?'Aktuelle Aufträge':`Archiv (${state.runs.filter(r=>r.mode!=='chat'&&r.archived).length})`}</button></div><div className="agent-run-list">{state.runs.filter(r=>r.mode!=='chat'&&Boolean(r.archived)===showArchived).map(run=><article className="agent-run" key={run.id}><div className="agent-run-heading"><span className={`agent-run-status ${run.status}`}>{run.status==='running'?<Clock3 size={13}/>:run.status==='review'?<ShieldCheck size={13}/>:<Check size={13}/>} {statuses[run.status]||run.status}</span><time>{new Date(run.created).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div><h2>{run.goal}</h2>{run.status==='running'?<div className="agent-running"><Companion appearance={state.appearance} tone={state.tone} active size={40}/><span>Plan und Entwürfe werden erstellt.</span><button className="secondary" onClick={()=>void act('stop',{id:run.id})}><Square size={12}/>Anhalten</button></div>:<>{run.error&&<p className="small-error">{run.error}</p>}{run.summary&&<div className="agent-summary"><ChatMarkdown>{run.summary}</ChatMarkdown></div>}</>}{run.steps.length>0&&<details className="agent-plan"><summary>Arbeitsplan<ChevronDown size={14}/></summary><ol>{run.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></details>}{run.actions.map(a=><section className="agent-action" key={a.id}><div className="agent-action-title">{a.kind==='note'?<FileText size={16}/>:<ListTodo size={16}/>}<strong>{a.title}</strong><span>{a.kind==='note'?'Notiz':'Aufgabe'}</span></div><div className="agent-action-content"><ChatMarkdown>{a.content}</ChatMarkdown></div>{a.status==='pending'?<div className="agent-approval"><span>In deinen Arbeitsplatz übernehmen?</span><button className="secondary" onClick={()=>void act('decide',{runId:run.id,actionId:a.id,decision:'reject'})}>Ablehnen</button><button className="primary" onClick={()=>void act('decide',{runId:run.id,actionId:a.id,decision:'approve'})}><Check size={14}/>Speichern</button></div>:<p className="agent-action-result">{a.status==='approved'?'Gespeichert':a.status==='blocked'?'Durch deine Regel blockiert':'Nicht übernommen'}</p>}</section>)}{run.status!=='running'&&<div className="agent-run-footer"><button onClick={()=>{setTab('memory');setKind('prefer');setMemory('');}}>Feedback merken<Brain size={13}/></button><details><summary>Aktivität</summary>{run.events.map((e,i)=><p key={i}>{new Date(e.at).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} · {e.text}</p>)}</details><button onClick={()=>void act('archive',{id:run.id,archived:!run.archived})}>{run.archived?'Wiederherstellen':'Archivieren'}</button></div>}</article>)}</div>
   <div className="agent-tools"><button onClick={()=>onOpen('notes')}><FileText size={17}/>Notizen<ChevronRight size={14}/></button><button onClick={()=>onOpen('tasks')}><ListTodo size={17}/>Aufgaben<ChevronRight size={14}/></button><button onClick={onChat}>Einfach chatten<ArrowUpRight size={15}/></button></div>
   <p className="agent-footnote">Aufträge laufen auf dem Haupt-Mac weiter, solange AEVORI und Ollama laufen. Der Agent erstellt Pläne und Inhalte. Er hat keinen Zugriff auf Browser, E-Mail, Einkäufe oder beliebige Dateien.</p>
  </>}
  {tab==='memory'&&<section className="agent-memory"><div className="agent-setting-row"><div><h2>Was dein Agent über dich weiß.</h2><p>Bestätigte Erinnerungen werden bei lokalen Chats und Agent-Aufträgen berücksichtigt.</p></div><button role="switch" aria-checked={state.memoryEnabled} aria-label="Gedächtnis verwenden" className={`toggle ${state.memoryEnabled?'on':''}`} onClick={()=>void act('profile',{memoryEnabled:!state.memoryEnabled})}><i/></button></div><form className="agent-memory-form" onSubmit={async e=>{e.preventDefault();if(await act('memory',{kind,content:memory}))setMemory('');}}><AevoriSelect label="Art der Erinnerung" value={kind} onValueChange={setKind} options={[{value:'prefer',label:'Das ist okay · bevorzugen'},{value:'avoid',label:'Das vermeiden'},{value:'fact',label:'Über mich'}]}/><textarea aria-label="Neue Erinnerung" value={memory} onChange={e=>setMemory(e.target.value)} maxLength={600} rows={3} placeholder={kind==='avoid'?'Zum Beispiel: Keine unnötig langen Einleitungen.':'Zum Beispiel: Ich mag klare Antworten mit einem konkreten nächsten Schritt.'}/><button className="primary" disabled={!memory.trim()}>Erinnerung bestätigen</button></form><p className="agent-footnote">Nur von dir bestätigte Inhalte werden gespeichert. Keine automatische Übernahme sensibler Details, kein Training der Modellgewichte. Beim Ausschalten bleiben Einträge gespeichert, werden aber nicht mitgegeben. Muse erhält diese Erinnerungen nicht.</p><div className="agent-memory-list">{state.memories.map(m=><article key={m.id}><span>{m.kind==='prefer'?'Bevorzugen':m.kind==='avoid'?'Vermeiden':'Über mich'}</span><p>{m.content}</p><button className="icon-button" aria-label={`Erinnerung löschen: ${m.content}`} onClick={()=>void act('forget',{id:m.id})}><Trash2 size={15}/></button></article>)}</div>{!state.memories.length&&<p className="agent-empty">Noch keine Erinnerungen. Du entscheidest, was bleibt.</p>}</section>}
  {tab==='rules'&&<section className="agent-rules"><h2>Du entscheidest, was okay ist.</h2><p>Diese Regeln werden von AEVORI geprüft. Der Agent kann sie nicht selbst ändern.</p>{[['note','Notizen speichern','Entwürfe in deinem Arbeitsplatz ablegen.'],['task','Aufgaben anlegen','Konkrete nächste Schritte übernehmen.']].map(([key,label,description])=><div className="agent-setting-row" key={key}><div><h3>{label}</h3><p>{description}</p></div><AevoriSelect label={label} value={state.policy[key as 'note'|'task']} onValueChange={value=>void act('profile',{policy:{[key]:value}})} options={[{value:'ask',label:'Erst prüfen'},{value:'allow',label:'Automatisch speichern'},{value:'block',label:'Nicht erlauben'}]}/></div>)}<div className="agent-boundaries"><LockKeyhole size={19}/><div><strong>Dein Arbeitsplatz bleibt abgegrenzt.</strong><p>Keine Befehle, E-Mails, Käufe oder externen Änderungen. Jeder Teamzugang hat eigene Aufträge und Erinnerungen.</p></div></div><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='aevori-agent.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Download size={15}/>Agent-Daten exportieren</button><button className="text-button" onClick={()=>onOpen('models')}>Lokale Modelle verwalten<ChevronRight size={14}/></button></section>}
 </div>;
}
