import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowUp,ArrowUpRight,Bell,Check,ChevronRight,Clock3,FileText,MessageCircle,PanelRightClose,PanelRightOpen,Plus,Square,Trash2,X} from 'lucide-react';
import Companion from './Companion';
import ChatMarkdown from './ChatMarkdown';
import type {AgentState} from './AgentWorkspace';
import './agent-messenger.css';
type Props={state:AgentState;act:(path:string,body:unknown)=>Promise<unknown>;onCharacter:()=>void;onWork:()=>void};
export default function AgentMessenger({state,act,onCharacter,onWork}:Props){
 const [mobile,setMobile]=useState(()=>matchMedia('(max-width: 760px)').matches);
 const [draft,setDraft]=useState(''),[mode,setMode]=useState<'chat'|'work'>('chat'),[sending,setSending]=useState(false),[details,setDetails]=useState(false),[selected,setSelected]=useState(''),[reminding,setReminding]=useState(false),[reminder,setReminder]=useState(''),[at,setAt]=useState(''),[count,setCount]=useState(60),[atBottom,setAtBottom]=useState(true);
 const scroller=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),read=useRef(''),initialized=useRef(false),contextPanel=useRef<HTMLElement>(null),detailsButton=useRef<HTMLButtonElement>(null),hadDetails=useRef(false);
 useEffect(()=>{const media=matchMedia('(max-width: 760px)'),change=()=>setMobile(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{if(details&&mobile)contextPanel.current?.focus();else if(!details&&hadDetails.current)detailsButton.current?.focus();hadDetails.current=details;},[details,mobile]);
 const closeDetails=()=>setDetails(false);
 const messages=state.messages??[],running=state.runs.find(r=>r.status==='running'),latest=messages.at(-1),lastReply=[...messages].reverse().find(m=>m.role==='assistant');
 const run=state.runs.find(r=>r.id===selected)??state.runs.find(r=>r.mode!=='chat'&&!r.archived),upcoming=(state.reminders??[]).filter(r=>!r.deliveredAt);
 useEffect(()=>{const el=scroller.current;if(el&&(!initialized.current||atBottom)){el.scrollTo({top:el.scrollHeight,behavior:initialized.current&&document.documentElement.dataset.motion!=='off'&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'instant'});initialized.current=true;}},[latest?.id,Boolean(running),atBottom]);
 useEffect(()=>{const mark=()=>{if(document.visibilityState!=='visible'||(mobile&&details)||!atBottom||!lastReply||lastReply.created<=state.readAt||read.current===lastReply.id)return;read.current=lastReply.id;void act('read',{id:lastReply.id}).then(result=>{if(!result)read.current='';}).catch(()=>{read.current='';});};mark();document.addEventListener('visibilitychange',mark);return()=>document.removeEventListener('visibilitychange',mark);},[lastReply?.id,state.readAt,atBottom,mobile,details,act]);
 async function send(){if(!draft.trim()||sending||running)return;setSending(true);try{const result=await act('start',{goal:draft,mode});if(result){setDraft('');setAtBottom(true);input.current?.focus();}}finally{setSending(false);}}
 return <div className={`agent-messenger ${details?'has-details':''}`} style={{'--agent-color':state.appearance.color} as CSSProperties}>
  <section className="agent-thread" inert={mobile&&details} aria-label={`Nachrichten mit ${state.name}`}>
   <header className="agent-thread-header"><button className="agent-contact" onClick={onCharacter} aria-label={`${state.name} gestalten`}><Companion appearance={state.appearance} active={!!running} size={56}/><span><strong>{state.name}</strong><small><i className="status-dot online"/>{running?(running.mode==='chat'?'Schreibt …':'Arbeitet an deinem Auftrag …'):'Dein Agent · auf deinem Mac'}</small></span></button><div><button className="icon-button" aria-label="Erinnerung planen" aria-expanded={reminding} onClick={()=>{setReminding(!reminding);setDetails(true);}}><Bell size={18}/></button><button ref={detailsButton} className="icon-button" aria-label={details?'Arbeitsbereich schließen':'Arbeitsbereich öffnen'} aria-expanded={details} onClick={()=>setDetails(!details)}>{details?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}</button></div></header>
   <div className="agent-thread-scroll" ref={scroller} onScroll={()=>{const el=scroller.current;if(el)setAtBottom(el.scrollHeight-el.scrollTop-el.clientHeight<100);}} role="log" aria-label="Agent-Nachrichten" aria-live="polite" aria-relevant="additions">
    {messages.length>count&&<button className="thread-older" onClick={()=>setCount(count+60)}>Ältere Nachrichten anzeigen</button>}
    {!messages.length&&<div className="agent-thread-intro"><button onClick={onCharacter} aria-label="Charakter gestalten"><Companion appearance={state.appearance} size={150}/></button><h1>Hey, ich bin {state.name}.</h1><p>Ein Ort für deine Ideen.<br/>Und jemanden, der mitdenkt.</p><div>{['Lass uns eine Idee durchdenken.','Was kannst du für mich tun?'].map(t=><button key={t} onClick={()=>{setDraft(t);input.current?.focus();}}>{t}<ArrowUpRight size={14}/></button>)}</div></div>}
    {messages.slice(-count).map((m,i,visible)=>{const prior=visible[i-1],newDay=!prior||new Date(prior.created).toDateString()!==new Date(m.created).toDateString(),result=state.runs.find(r=>r.id===m.runId);return <div key={m.id} className="agent-message-entry">{newDay&&<p className="thread-date">{new Date(m.created).toLocaleDateString('de-DE',{weekday:'short',day:'numeric',month:'long'})}</p>}<article className={`agent-chat-message ${m.role} ${m.kind||''}`}>
     {m.role==='assistant'&&<Companion appearance={state.appearance} size={34}/>}
     <div className="agent-chat-message-content"><div className="agent-chat-bubble">{m.kind==='reminder'&&<span className="thread-kind"><Bell size={12}/>Deine Erinnerung</span>}{m.kind==='work'&&<span className="thread-kind"><FileText size={12}/>Auftrag</span>}<ChatMarkdown>{m.content}</ChatMarkdown></div>
      <div className="agent-message-meta"><time dateTime={new Date(m.created).toISOString()}>{new Date(m.created).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</time>{m.role==='user'&&<span>{result?.status==='running'?'Zugestellt':'Gesendet'}</span>}{m.kind==='result'&&result&&<button onClick={()=>{setSelected(result.id);setDetails(true);}}>{result.actions.some(a=>a.status==='pending')?'Ergebnis prüfen':'Auftrag ansehen'}<ChevronRight size={12}/></button>}</div>
     </div></article></div>;})}
    {running&&<div className="agent-chat-message assistant agent-is-typing"><Companion appearance={state.appearance} active size={34}/><div><div className="typing-dots" role="status" aria-label={`${state.name} ${running.mode==='chat'?'schreibt':'arbeitet'}`}><i/><i/><i/></div><small>{running.mode==='chat'?'Schreibt …':'Dein Auftrag wird vorbereitet …'}</small></div></div>}
   </div>
   <footer className="agent-thread-footer">
    {!atBottom&&<button className="thread-latest" onClick={()=>{setAtBottom(true);}}>Zu den neuesten Nachrichten ↓</button>}
    <form className="agent-message-composer" onSubmit={e=>{e.preventDefault();void send();}}><textarea ref={input} aria-label={`Nachricht an ${state.name}`} rows={1} value={draft} maxLength={6000} placeholder={mode==='chat'?`Nachricht an ${state.name} …`:'Was soll dein Agent für dich vorbereiten?'} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><div className="agent-composer-toolbar"><div className="agent-compose-mode" aria-label="Art der Nachricht"><button type="button" aria-pressed={mode==='chat'} onClick={()=>setMode('chat')}><MessageCircle size={13}/>Nachricht</button><button type="button" aria-pressed={mode==='work'} onClick={()=>setMode('work')}><Plus size={13}/>Auftrag</button></div>{running?<button type="button" className="agent-send" aria-label="Agent anhalten" onClick={()=>void act('stop',{id:running.id})}><Square size={15}/></button>:<button className="agent-send" aria-label="Nachricht senden" disabled={sending||!draft.trim()}><ArrowUp size={18}/></button>}</div></form>
    <p>Privat auf deinem Mac. {mode==='work'?'Entwürfe prüfst du vor dem Speichern.':'Ein Gespräch, das bleibt.'}</p>
   </footer>
  </section>
  {details&&<aside ref={contextPanel} tabIndex={-1} className="agent-context" role={mobile?'dialog':'complementary'} aria-modal={mobile?true:undefined} aria-label="Arbeitsbereich" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeDetails();}if(mobile&&e.key==='Tab'){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input, textarea, [href], summary'));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===e.currentTarget)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><div className="agent-context-heading"><span>Arbeitsbereich</span><button className="icon-button" aria-label="Details schließen" onClick={closeDetails}><X size={16}/></button></div>
   {reminding&&<form className="agent-reminder-form" onSubmit={async e=>{e.preventDefault();const result=await act('remind',{text:reminder,at:new Date(String(new FormData(e.currentTarget).get('reminderAt'))).getTime()});if(result){setReminding(false);setReminder('');setAt('');}}}><h2>Ich melde mich bei dir.</h2><p>Dein Agent schickt dir zum gewählten Zeitpunkt eine Nachricht hier im Chat.</p><label>Woran erinnern?<input required maxLength={500} value={reminder} onChange={e=>setReminder(e.target.value)} placeholder="Zum Beispiel: Entwurf prüfen"/></label><label>Datum & Uhrzeit<input required name="reminderAt" type="datetime-local" value={at} onInput={e=>setAt(e.currentTarget.value)} onChange={e=>setAt(e.target.value)}/></label><button className="primary">Erinnerung speichern<Bell size={13}/></button><small>AEVORI muss auf dem Mac laufen. Nach einer Pause kommt die Nachricht beim nächsten Start.</small></form>}
   {upcoming.length>0&&<section className="agent-upcoming"><h2>Geplant</h2>{upcoming.map(r=><div key={r.id}><Bell size={14}/><span>{r.text}<small>{new Date(r.at).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></span><button className="icon-button" aria-label={`Erinnerung entfernen: ${r.text}`} onClick={()=>void act('cancel-reminder',{id:r.id})}><Trash2 size={14}/></button></div>)}</section>}
   {run?<section className="agent-context-run"><span className="context-eyebrow">{run.status==='running'?'IN ARBEIT':run.actions.some(a=>a.status==='pending')?'BEREIT ZUM PRÜFEN':'DEIN AUFTRAG'}</span><h2>{run.goal}</h2>{run.steps.length>0&&<ol className="context-plan">{run.steps.map((step,i)=><li key={i}><span>{i+1}</span>{step}</li>)}</ol>}{run.actions.map(a=><article className="context-artifact" key={a.id}><header><FileText size={16}/><strong>{a.title}</strong></header><div><ChatMarkdown>{a.content}</ChatMarkdown></div><footer>{a.status==='pending'?<><button className="secondary" onClick={()=>void act('decide',{runId:run.id,actionId:a.id,decision:'reject'})}>Ablehnen</button><button className="primary" onClick={()=>void act('decide',{runId:run.id,actionId:a.id,decision:'approve'})}><Check size={13}/>Speichern</button></>:<span>{a.status==='approved'?'In deinem Arbeitsplatz gespeichert':a.status==='blocked'?'Durch deine Regel blockiert':'Nicht übernommen'}</span>}</footer></article>)}{run.error&&<p className="small-error">{run.error}</p>}<details className="context-activity"><summary><Clock3 size={14}/>Aktivität</summary>{run.events.map((e,i)=><p key={i}>{e.text}</p>)}</details><button className="text-button" onClick={onWork}>Alle Aufträge<ArrowUpRight size={14}/></button></section>:!reminding&&<div className="agent-context-empty"><Companion appearance={state.appearance} size={96}/><h2>Platz für das, was entsteht.</h2><p>Pläne, Notizen und nächste Schritte erscheinen hier, sobald du einen Auftrag startest.</p><button className="secondary" onClick={()=>{setMode('work');input.current?.focus();}}>Ersten Auftrag schreiben<ArrowUpRight size={14}/></button></div>}
  </aside>}
 </div>;
}
