import {useRef,useState,type ChangeEvent} from 'react';
import {ArrowUpRight,Check,ChevronRight,ImagePlus,MessageCircle,NotebookPen,Terminal,Link2} from 'lucide-react';
import type {workspaceStorage} from '../storage';
import './muse.css';
import Companion from './Companion';

export type MuseAppearance={name:string;avatar:string};
export const defaultMuse:MuseAppearance={name:'Muse',avatar:''};
export function MuseAvatar({appearance,active=false,small=false}:{appearance:MuseAppearance;active?:boolean;small?:boolean}){
 return <span className={`muse-avatar ${small?'small':''} ${active?'working':''}`}>{appearance.avatar.startsWith('data:image/')?<img src={appearance.avatar} alt={small?'':appearance.name}/>:<Companion tone="lavender" active={active} size={small?32:180}/>}</span>;
}
type Props={appearance:MuseAppearance;onAppearance:(a:MuseAppearance)=>void;storage:ReturnType<typeof workspaceStorage>;connected:boolean;busy:boolean;status:string;owner:boolean;cliInstalled:boolean;model:string;tasks:{id:string;text:string;done:boolean}[];onTask:(id:string)=>void;onOpen:(view:'tasks'|'notes'|'team')=>void;onStart:(text?:string,mode?:string)=>void;onConnect:()=>void};
export default function MuseWorkspace(p:Props){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState(p.appearance.name),[error,setError]=useState('');
 const upload=useRef<HTMLInputElement>(null);
 const save=(next:MuseAppearance)=>{try{p.storage.write('aevori-muse-appearance',next);p.onAppearance(next);setError('');return true;}catch{setError('Dein Browserspeicher ist voll. Das Bild wurde nicht gespeichert.');return false;}};
 const importAvatar=async(e:ChangeEvent<HTMLInputElement>)=>{
  const file=e.target.files?.[0];e.target.value='';if(!file)return;
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024){setError('Wähle ein PNG-, JPG- oder WebP-Bild mit höchstens 1 MB.');return;}
  try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});await new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve();image.onerror=reject;image.src=data;});save({...p.appearance,avatar:data});}catch{setError('Das Bild konnte nicht geöffnet werden. Wähle eine andere Datei.');}
 };
 const ideas=[{icon:NotebookPen,title:'Aus einer Idee wird ein Plan.',detail:'Nächste Schritte finden',mode:'general',prompt:'Hilf mir, aus meiner Idee einen konkreten Plan mit klaren nächsten Schritten zu machen. Frag mich zuerst, was ich erreichen möchte.'},{icon:MessageCircle,title:'Den richtigen Ton treffen.',detail:'Gemeinsam an einem Text arbeiten',mode:'writing',prompt:'Hilf mir, einen Text zu verbessern. Frag mich zuerst nach meinem Entwurf, der Zielgruppe und dem gewünschten Ton.'},{icon:Terminal,title:'Etwas Eigenes entwickeln.',detail:'Code und Design durchdenken',mode:'code',prompt:'Lass uns eine kleine App entwickeln. Kläre mit mir die wichtigste Funktion und schlage einen überschaubaren ersten Schritt vor.'}];
 return <div className="muse-workspace">
  <div className="muse-heading"><div className="muse-wordmark"><strong>Muse Spark</strong><span>in AEVORI</span></div><span className="muse-connection"><i className={p.connected?'ready':''}/>{p.connected?'Mit Meta verbunden':'Noch nicht verbunden'}</span></div>
  <div className="muse-intro">
   <div className="muse-intro-copy"><span className="muse-kicker">Ein Gedanke. Viele Möglichkeiten.</span><h1>Mach mehr<br/>aus deinen Ideen.</h1><p>Ein Ort zum Denken, Schreiben und Weiterkommen. Mit Muse Spark und deinem persönlichen Gegenüber.</p><div className="muse-start"><button className="primary" disabled={p.busy} onClick={()=>p.onStart()}>{p.connected?'Mit Muse chatten':'Muse verbinden'}<ArrowUpRight size={17}/></button><a href="https://muse.ai" target="_blank" rel="noreferrer">Dein Muse-Konto öffnen<ArrowUpRight size={14}/></a></div><span className="muse-cloud-note">Muse Spark verarbeitet deine Anfragen bei Meta.</span></div>
   <div className="muse-character"><MuseAvatar appearance={p.appearance} active={p.busy&&p.connected}/><div className="muse-character-name">{p.appearance.name}<button className="icon-button" aria-label="Muse gestalten" onClick={()=>{setDraft(p.appearance.name);setEditing(!editing);}}><ImagePlus size={16}/></button></div><p role="status">{p.connected?(p.busy?p.status:'Bereit für deinen nächsten Gedanken.'):'Deine Muse wartet auf eine Verbindung.'}</p><span className="muse-attribution">{!p.appearance.avatar.startsWith('data:image/')?<span>AEVORI-Charakter</span>:'Dein Avatar · auf diesem Gerät gespeichert'}</span></div>
  </div>
  {editing&&<form className="muse-personalize" onSubmit={e=>{e.preventDefault();if(draft.trim()&&save({...p.appearance,name:draft.trim()}))setEditing(false);}}><label>Name deiner Muse<input value={draft} maxLength={32} onChange={e=>setDraft(e.target.value)} required/></label><input ref={upload} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" aria-label="Muse-Avatar hochladen" onChange={e=>void importAvatar(e)}/><button className="secondary" type="button" onClick={()=>upload.current?.click()}><ImagePlus size={16}/>Eigenes Bild</button><button type="button" className="text-button" onClick={()=>save({...p.appearance,avatar:defaultMuse.avatar})}>AEVORI-Figur</button><button className="primary" disabled={!draft.trim()}>Speichern</button><p>Dein Name und Bild bleiben in diesem Browser. Verwende nur Bilder, für die du die Nutzungsrechte hast.</p></form>}
  {error&&<p className="error-banner" role="alert">{error}</p>}
  <div className="muse-section-heading"><h2>Womit fangen wir an?</h2><span>Ideen für euren ersten Schritt</span></div>
  <div className="muse-ideas">{ideas.map(idea=><button key={idea.mode} disabled={p.busy} onClick={()=>p.onStart(idea.prompt,idea.mode)}><idea.icon size={20}/><strong>{idea.title}</strong><span>{idea.detail}<ArrowUpRight size={15}/></span></button>)}</div>
  <div className="muse-lower"><section className="muse-goals"><div className="muse-section-heading"><h2>Deine nächsten Schritte</h2><button className="text-button" onClick={()=>p.onOpen('tasks')}>Alle Aufgaben<ChevronRight size={14}/></button></div>{p.tasks.some(t=>!t.done)?p.tasks.filter(t=>!t.done).slice(0,3).map(t=><div className="muse-goal" key={t.id}><button aria-label={`Erledigen: ${t.text}`} onClick={()=>p.onTask(t.id)}><Check size={14}/></button><span>{t.text}</span></div>):<p>Halte fest, was dir wichtig ist. Aus Antworten kannst du direkt eine Aufgabe erstellen.</p>}<div className="muse-shortcuts"><button onClick={()=>p.onOpen('notes')}><NotebookPen size={16}/>Deine Notizen</button><button onClick={()=>p.onOpen('team')}><Link2 size={16}/>Mit Freunden arbeiten</button></div></section><section className="muse-setup"><h2>Deine Verbindung</h2><p><i className={p.connected?'ready':''}/>{p.connected?p.model:'Muse Spark · Standard'}</p><span>Text, Bilder und einstellbarer Denkaufwand. Die Verbindung nutzt deinen Meta-API-Schlüssel.</span>{p.owner&&<button className="text-button" disabled={p.busy} onClick={p.onConnect}>{p.connected?'Verbindung bearbeiten':'API-Schlüssel hinterlegen'}<ChevronRight size={14}/></button>}<div className="muse-cli"><Terminal size={15}/><span>{p.cliInstalled?'Muse Code ist auf diesem Mac installiert.':'Muse Code ist separat erhältlich.'}</span><a href="https://dev.meta.ai/docs/muse-code/auth" target="_blank" rel="noreferrer" aria-label="Muse Code Anmeldung"><ArrowUpRight size={14}/></a></div></section></div>
  <p className="muse-limit">Hier arbeitet Muse Spark in AEVORI. Dein persönliches Muse-Konto, seine Erinnerungen und Hintergrundaktionen werden nicht synchronisiert. Antworten kannst du als Notizen oder Aufgaben übernehmen.</p>
 </div>;
}
