import ModelLogo from './ModelLogo';
import {modelLabel} from '../model-catalog';
import BrandLogo from './BrandLogo';
import LiveChart from './LiveChart';
import {Network,Monitor,StickyNote,CheckCheck,ArrowUpRight,Plus,Check} from '../MotionIcon';
type Props={model:string;connected:boolean;ready:number;cpu:number|null;memory:string;history:number[];notes:number;noteTitle:string;tasks:number;done:number;open:(view:'models'|'system'|'notes'|'tasks'|'pool')=>void;addNote:()=>void};
export default function QuickTools({model,connected,ready,cpu,memory,history,notes,noteTitle,tasks,done,open,addNote}:Props){
 const points=history.map((v,i)=>`${i*240/Math.max(1,history.length-1)},${58-v*.48}`).join(' ');
 return <section className="workspace-tools"><div className="workspace-tools-heading"><h2>Dein Arbeitsplatz.</h2><span>Alles griffbereit</span></div><div className="workspace-tool-grid">
 <button className="workspace-tool model-workspace" onClick={()=>open('models')}><div className="workspace-tool-top"><span><Network size={17}/>Intelligenz</span><ArrowUpRight size={16}/></div><div className="model-connection-art" aria-hidden="true"><span className="connection-mark"><BrandLogo symbol/></span><i/><span className="connection-model"><ModelLogo model={model} size={25}/></span><span className="connection-line"/><span className="connection-peer"><Monitor size={19}/></span></div><div className="workspace-tool-copy"><h3>{connected?modelLabel(model):'Deine Modelle. Dein Raum.'}</h3><p>{connected?'Bereit für deinen nächsten Gedanken.':'Verbinde lokale Modelle oder deine eigene API.'}</p></div><div className="workspace-tool-foot"><span><i className={`status-dot ${connected?'online':''}`}/>{connected?'Verbunden':'Verbindung einrichten'}</span><span>{ready?`${ready} ${ready===1?'Mac bereit':'Macs bereit'}`:'Modelle öffnen'}</span></div></button>
 <button className="workspace-tool device-workspace" onClick={()=>open('system')}><div className="workspace-tool-top"><span><Monitor size={17}/>Dein Mac</span><ArrowUpRight size={16}/></div><div className="device-readout"><strong>{cpu===null?'—':cpu}<span>{cpu!==null?'%':''}</span></strong><span>CPU-Auslastung</span></div><LiveChart values={history} compact/><div className="workspace-tool-foot"><span>Arbeitsspeicher</span><span>{memory}</span></div></button>
 <button className="workspace-tool compact-workspace notes-workspace-link" onClick={()=>notes?open('notes'):addNote()}><span className="workspace-tool-icon"><StickyNote size={23}/></span><div><h3>Gedanken festhalten</h3><p>{notes?noteTitle||'Deine Notizen öffnen':'Eine neue Notiz beginnen'}</p></div><span className="workspace-tool-count">{notes||<Plus size={17}/>}</span></button>
 <button className="workspace-tool compact-workspace tasks-workspace-link" onClick={()=>open('tasks')}><span className="workspace-tool-icon"><CheckCheck size={23}/></span><div><h3>Platz im Kopf</h3><p>{tasks?`${tasks-done} offen · ${done} erledigt`:'Was möchtest du heute schaffen?'}</p></div><span className="workspace-task-progress" style={{'--progress':`${tasks?done/tasks*100:0}%`} as React.CSSProperties}>{tasks&&done===tasks?<Check size={14}/>:tasks-done}</span></button>
 </div></section>;
}
