import {AppShell} from './components/app-shell';
import {AppSidebar} from './components/app-sidebar';
import type {View,SidebarNavGroup} from './components/app-shared';
import AgentWorkspace,{useAgent} from './components/AgentWorkspace';
import Companion from './components/Companion';
import SettingsPage,{type SettingsTab} from './components/SettingsPage';
import SmoothHeight from './components/SmoothHeight';
import MuseWorkspace,{MuseAvatar,defaultMuse,type MuseAppearance} from './components/MuseWorkspace';
import React,{useEffect,useState,useRef,useMemo} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import ChatMessage from './components/ChatMessage';
import {workspaceStorage} from './storage';
import {branchAt,wireContent,type Message} from './chat-state';
import AevoriMark from './AevoriMark';
import {imageDataUrl,setAttachmentWorkspace,type PreparedAttachments,type ChatImage,type ChatFile} from './attachments';
import ChatInput from './components/ChatInput';
import TeamPanel,{type Session} from './components/TeamPanel';
import ModelInstall from './components/ModelInstall';
import {modelLabel,modelInfo} from './model-catalog';
import BrandLogo from './components/BrandLogo';
import ModelLogo from './components/ModelLogo';
import ModelEcosystem from './components/ModelEcosystem';
import ProfileSetup from './components/ProfileSetup';
import MacImage from './components/MacImage';
import LiveChart from './components/LiveChart';
import ProcessIcon from './components/ProcessIcon';
import NotesPanel from './components/NotesPanel';
import ModelSelect from './components/ModelSelect';
import AevoriSelect from './components/AevoriSelect';
import PoolPanel,{type PoolState} from './PoolPanel';
import {ArrowUp,ArrowUpRight,AudioLines,Check,CheckCheck,ChevronDown,ChevronRight,Command,Cpu,HardDrive,MessageCircle,Monitor,Network,Plus,Search,Settings,ShieldCheck,Sparkles,Square,StickyNote,Timer,Trash2,X,RefreshCw,Menu,Activity,MemoryStick,ArrowLeft,Link2,PanelLeft,CheckCircle2,MoreHorizontal,Copy,Send,Wifi,FileText,ChevronUp} from './MotionIcon';

type Model={id:string;size?:number;parameters?:string;quantization?:string};
type Provider={type:'ollama'|'compatible';baseUrl:string;local:boolean;hasKey:boolean;brand?:string|null};
type Stats={hardware:{name:string;chip:string;cores:number;os:string};cpu:number;memory:{total:number;used:number};disk:null|{total:number;used:number;free:number};uptime:number;processes:{pid:number;cpu:number;memory:number;name:string;icon?:string}[];at:string};
type Chat={id:string;title:string;messages:Message[];updated:number;deletedAt?:number};
type Task={id:string;text:string;priority:'low'|'medium'|'high';done:boolean};
type Note={id:string;title:string;body:string;updated:number};
const NAV:{id:View;name:string;icon:typeof Cpu}[]=[{id:'chat',name:'Chat',icon:MessageCircle},{id:'agent',name:'Dein Agent',icon:Activity},{id:'muse',name:'Muse',icon:Sparkles},{id:'notes',name:'Notizen',icon:StickyNote},{id:'tasks',name:'Aufgaben',icon:CheckCheck},{id:'models',name:'Modelle',icon:Cpu},{id:'system',name:'Dein Mac',icon:Monitor},{id:'pool',name:'Mac-Pool',icon:Network},{id:'team',name:'Team',icon:ShieldCheck},{id:'settings',name:'Einstellungen',icon:Settings}];
const GB=1024**3;
const bytes=(v:number)=>`${(v/GB).toFixed(v/GB<10?1:0)} GB`;
const uid=()=>crypto.randomUUID();
function Mark({small=false,busy=false}:{small?:boolean;busy?:boolean}){return <AevoriMark small={small} busy={busy}/>}
function Modal({open,onOpenChange,title,description,children,className=''}:{open:boolean;onOpenChange:(b:boolean)=>void;title:string;description?:string;children:React.ReactNode;className?:string}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${className}`}><Dialog.Title>{title}</Dialog.Title><Dialog.Description className={description?'dialog-description':'sr-only'}>{description||title}</Dialog.Description><Dialog.Close className="icon-button close" aria-label="Schließen"><X size={19}/></Dialog.Close><SmoothHeight>{children}</SmoothHeight></Dialog.Content></Dialog.Portal></Dialog.Root>}
export default function App({session}:{session:Session}){
  const isOwner=session.role==='owner';
  const agent=useAgent();
  const storage=useMemo(()=>workspaceStorage(session.role,session.id),[session.role,session.id]);
  const saved=<T,>(key:string,fallback:T):T=>storage.read(key,fallback);
  setAttachmentWorkspace(isOwner?'owner':session.id);
  useEffect(()=>{const ping=()=>void fetch('/api/team/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});ping();const t=setInterval(ping,15000);return()=>clearInterval(t);},[]);
  const [view,setView]=useState<View>('chat'),[settingsTab,setSettingsTab]=useState<SettingsTab>('profile'),[agentSection,setAgentSection]=useState('chat'),[connectOpen,setConnectOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState('');
  const mainContentRef=useRef<HTMLElement>(null);
  useEffect(()=>{mainContentRef.current?.scrollTo({top:0});},[view]);
  const [theme,setTheme]=useState(saved('aevori-theme','dark')),[glass,setGlass]=useState(saved('aevori-glass',true));
  const [stats,setStats]=useState<Stats|null>(null),[systemError,setSystemError]=useState(''),[history,setHistory]=useState<number[]>([]);
  const [models,setModels]=useState<Model[]>([]),[provider,setProvider]=useState<Provider>({type:'ollama',baseUrl:'http://127.0.0.1:11434',local:true,hasKey:false}),[connected,setConnected]=useState(false),[model,setModel]=useState(saved('aevori-model','')),[connectionError,setConnectionError]=useState(''),[refreshing,setRefreshing]=useState(false);
  const [museAppearance,setMuseAppearance]=useState<MuseAppearance>(saved('aevori-muse-appearance',defaultMuse)),[museCliInstalled,setMuseCliInstalled]=useState(false);
  const museDraft=useRef<{text:string;mode:string}|null>(null);
  const museConnected=connected&&provider.brand==='meta-muse';
  useEffect(()=>{if(isOwner)void fetch('/api/muse/status').then(r=>r.ok?r.json():null).then(d=>setMuseCliInstalled(d?.cliInstalled===true)).catch(()=>{});},[isOwner]);
  const [form,setForm]=useState({type:'ollama',baseUrl:'http://127.0.0.1:11434',apiKey:''}),[connecting,setConnecting]=useState(false),[formError,setFormError]=useState('');
  const [chats,setChats]=useState<Chat[]>(saved('aevori-chats',[])),[chatId,setChatId]=useState<string|null>(null),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[chatError,setChatError]=useState(''),[includeContext,setIncludeContext]=useState(false),[status,setStatus]=useState(''),[requestStartedAt,setRequestStartedAt]=useState<number|null>(null);
  const [notes,setNotes]=useState<Note[]>(saved('aevori-notes',[])),[noteId,setNoteId]=useState<string|null>(null),[tasks,setTasks]=useState<Task[]>(saved('aevori-tasks',[])),[taskText,setTaskText]=useState(''),[priority,setPriority]=useState<Task['priority']>('medium');

  const [workMode,setWorkMode]=useState(saved('aevori-work-mode','general'));
  const [editing,setEditing]=useState<{index:number;text:string}|null>(null),[taskDraft,setTaskDraft]=useState<string|null>(null);
  const [responseLength,setResponseLength]=useState(saved('aevori-response-length','normal')),[creativity,setCreativity]=useState('balanced'),[reasoning,setReasoning]=useState('auto'),[thinking,setThinking]=useState<(string|boolean)[]>([]);
  useEffect(()=>{setReasoning('auto');setThinking([]);if(!model||model==='__auto__')return;let alive=true;void fetch('/api/model/options',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model})}).then(r=>r.json()).then(d=>{if(alive)setThinking(d.thinking||[]);}).catch(()=>{});return()=>{alive=false;};},[model,provider.baseUrl]);
  useEffect(()=>{storage.write('aevori-work-mode',workMode);storage.write('aevori-response-length',responseLength);},[workMode,responseLength]);
  const [pool,setPool]=useState<PoolState>({nodes:[],sharing:false}),[usePool,setUsePool]=useState(false);
  const [profileName,setProfileName]=useState(session.profileConfigured?session.name||'':session.role==='member'?session.name||'':''),[motion,setMotion]=useState(saved('aevori-motion',true));
  const [profileConfigured,setProfileConfigured]=useState(session.profileConfigured===true),[setupOpen,setSetupOpen]=useState(!session.profileConfigured);
  const refreshPool=async()=>{try{const r=await fetch('/api/pool');if(r.ok)setPool(await r.json());}catch{/* Keep last known pool until the next refresh. */}};
  useEffect(()=>{void refreshPool();const t=setInterval(refreshPool,6000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(profileConfigured)storage.write('aevori-name',profileName);},[profileName,profileConfigured]);
  useEffect(()=>{storage.write('aevori-motion',motion);document.documentElement.dataset.motion=motion?'on':'off';window.dispatchEvent(new Event('aevori-motion-change'));},[motion]);
  const requestInFlight=useRef(false),contextProvider=useRef(''),followReply=useRef(true),conversation=useRef<HTMLDivElement>(null);
  const [toast,setToast]=useState(''),[undoChat,setUndoChat]=useState<string|null>(null);const abort=useRef<AbortController|null>(null),end=useRef<HTMLDivElement>(null);
  const visibleChats=chats.filter(c=>!c.deletedAt);
  const chat=chats.find(c=>c.id===chatId),messages=chat?.messages||[],note=notes.find(n=>n.id===noteId);
  const go=(next:View)=>{if(next==='agent')setAgentSection('chat');setView(!isOwner&&next==='system'?'team':next);setSearchOpen(false);};
  const notify=(text:string)=>{setUndoChat(null);setToast(text);};
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>{setToast('');setUndoChat(null);},7000);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;storage.write('aevori-theme',theme);},[theme]);
  useEffect(()=>{storage.write('aevori-glass',glass);},[glass]);
  useEffect(()=>{try{storage.write('aevori-chats',chats);storage.write('aevori-notes',notes);storage.write('aevori-tasks',tasks);}catch{notify('Gerätespeicher voll. Änderungen können nicht gespeichert werden.');}},[chats,notes,tasks]);
  useEffect(()=>{
    if(!agent.state)return;
    const imported=storage.read<string[]>('aevori-agent-imports',[]),fresh=agent.state.artifacts.filter(a=>!imported.includes(a.id));
    if(!fresh.length)return;
    const nextNotes=[...fresh.filter(a=>a.kind==='note'&&!notes.some(n=>n.id==='agent-'+a.id)).map(a=>({id:'agent-'+a.id,title:a.title,body:a.content,updated:a.created})),...notes];
    const nextTasks=[...fresh.filter(a=>a.kind==='task'&&!tasks.some(t=>t.id==='agent-'+a.id)).map(a=>({id:'agent-'+a.id,text:a.title+' — '+a.content,priority:'medium' as const,done:false})),...tasks];
    try{storage.write('aevori-notes',nextNotes);storage.write('aevori-tasks',nextTasks);storage.write('aevori-agent-imports',[...imported,...fresh.map(a=>a.id)]);setNotes(nextNotes);setTasks(nextTasks);}catch{notify('Gerätespeicher voll. Dein Agent-Ergebnis bleibt auf dem Mac gespeichert.');}
  },[agent.state,storage]);
  useEffect(()=>{storage.write('aevori-model',model);},[model]);
  useEffect(()=>{if(!isOwner)return;let alive=true;const c=new AbortController();const poll=async()=>{try{const r=await fetch('/api/system',{signal:c.signal});if(!r.ok)throw new Error();const s=await r.json();if(alive){setStats(s);setSystemError('');setHistory(h=>[...h.slice(-39),s.cpu]);}}catch{if(alive)setSystemError('Aevori ist nicht mit dem lokalen Dienst verbunden.');}};void poll();const timer=setInterval(poll,3000);return()=>{alive=false;c.abort();clearInterval(timer);};},[]);
  const refreshModels=async()=>{setRefreshing(true);try{const r=await fetch('/api/models');const data=await r.json();if(!data.provider)throw new Error('Keine Anbieterinformationen.');setModels(data.models||[]);setProvider(data.provider);if(contextProvider.current!==data.provider.baseUrl){setIncludeContext(false);contextProvider.current=data.provider.baseUrl;}setConnected(data.connected);setConnectionError(data.error||'');setModel((old:string)=>old==='__auto__'?'__auto__':(data.models||[]).some((m:Model)=>m.id===old)?old:data.models?.length?'__auto__':'');}catch{setConnected(false);setConnectionError('Lokaler Dienst nicht erreichbar.');}finally{setRefreshing(false);}};
  useEffect(()=>{void refreshModels();return()=>abort.current?.abort();},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!setupOpen&&(e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearchOpen(v=>!v);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[setupOpen]);
  useEffect(()=>{followReply.current=true;},[chatId]);
  useEffect(()=>{const box=conversation.current;if(box&&followReply.current)box.scrollTop=box.scrollHeight;},[messages.at(-1)?.content,busy,chatId]);
  const restoreChat=(id:string)=>{setChats(cs=>cs.map(c=>c.id===id?{...c,deletedAt:undefined}:c));setUndoChat(null);setToast('Chat wiederhergestellt.');};
  const deleteChat=(id:string)=>{if(busy&&chatId===id)return;setChats(cs=>cs.map(c=>c.id===id?{...c,deletedAt:Date.now()}:c));if(chatId===id){setChatId(null);setChatError('');}setUndoChat(id);setToast('Chat gelöscht.');};
  const newChat=()=>{if(busy)return;setChatId(null);setPrompt('');setChatError('');go('chat');};
  const openConnect=()=>{if(!isOwner){notify('Neue Verbindungen richtet der Gastgeber am Haupt-Mac ein.');return;}setForm({type:provider.type,baseUrl:provider.baseUrl,apiKey:''});setFormError('');setConnectOpen(true);};
  const openMuseConnect=()=>{if(!isOwner){notify('Die Muse-Verbindung richtet dein Gastgeber am Haupt-Mac ein.');return;}setForm({type:'compatible',baseUrl:'https://api.meta.ai/v1',apiKey:''});setFormError('');setConnectOpen(true);};
  const startMuse=(text='',mode='general')=>{if(busy)return;if(!museConnected){museDraft.current={text,mode};openMuseConnect();return;}setUsePool(false);newChat();setModel(models.find(m=>m.id==='muse-spark-1.3')?.id||models[0]?.id||'');setPrompt(text);setWorkMode(mode);};
  const connect=async(e:React.FormEvent)=>{e.preventDefault();setConnecting(true);setFormError('');try{const r=await fetch('/api/provider',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setProvider(d.provider);setModels(d.models);setModel(d.models[0]?.id||'');setConnected(true);setConnectionError('');setIncludeContext(false);setUsePool(false);setChatId(null);setChatError('');setPrompt(d.provider.brand==='meta-muse'?museDraft.current?.text||'':'');if(d.provider.brand==='meta-muse')setWorkMode(museDraft.current?.mode||'general');museDraft.current=null;go('chat');contextProvider.current=d.provider.baseUrl;setConnectOpen(false);setForm(f=>({...f,apiKey:''}));notify('Verbindung hergestellt.');}catch(e){setFormError(e instanceof Error?e.message:'Verbindung fehlgeschlagen.');}finally{setConnecting(false);}};
  const send=async(text=prompt,attachments?:PreparedAttachments,branch?:Message[])=>{
    if(!text.trim()||requestInFlight.current)return false;
    if(!usePool&&(!connected||!model)){openConnect();return false;}
    const outgoing:Message[]=[...(branch??messages),{role:'user',content:text.trim(),...(attachments?.images.length?{images:attachments.images}:{}),...(attachments?.files.length?{files:attachments.files}:{})}];
    const id=branch?uid():chatId||uid();
    const branchTitle=(chat?.title||text.slice(0,35)).replace(/(?: · Variante(?: \d+)?)+$/, '');
    const variant=chats.filter(c=>c.title.startsWith(branchTitle+' · Variante')).length+1;
    if(outgoing.length>78){setChatError('Dieser Chat hat sein Nachrichtenlimit erreicht. Bitte einen neuen Chat starten.');return false;}
    requestInFlight.current=true;setBusy(true);setChatError('');setRequestStartedAt(Date.now());setStatus('Anhänge und Anfrage vorbereiten …');
    const controller=new AbortController();abort.current=controller;
    let started=false,reply='';let metadata:Partial<Message>={};
    const updateReply=(patch:Partial<Message>)=>{metadata={...metadata,...patch};setChats(cs=>cs.map(c=>c.id===id?{...c,messages:[...outgoing,{role:'assistant',content:reply,...metadata}]}:c));};
    try{
      if(!usePool&&model!=='__auto__'&&provider.type==='ollama'&&outgoing.some(m=>m.images?.length)){
        const response=await fetch('/api/model/options',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model}),signal:controller.signal});
        if(!response.ok)throw new Error('Modellfähigkeiten konnten nicht geprüft werden.');
        const capabilities=await response.json();
        if(capabilities.vision!==true)throw new Error(`${modelLabel(model)} kann keine Bilder lesen. Wähle Automatisch oder ein Modell mit „Text + Bilder“.`);
      }
      const wireMessages=await Promise.all(outgoing.map(async m=>({role:m.role,content:wireContent(m),...(m.images?.length?{images:await Promise.all(m.images.map(imageDataUrl))}:{})})));
      if(controller.signal.aborted)throw new DOMException('Abgebrochen','AbortError');
      if(JSON.stringify(wireMessages).length>10*1024**2)throw new Error('Dieser Chat enthält zu viele Bilddaten. Bitte einen neuen Chat starten.');
      setChatId(id);go('chat');setPrompt('');started=true;followReply.current=true;
      setChats(old=>{const existing=old.find(c=>c.id===id);return [{id,title:branch?`${branchTitle} · Variante ${variant}`:existing?.title||text.slice(0,42),messages:[...outgoing,{role:'assistant',content:''}],updated:Date.now()},...old.filter(c=>c.id!==id)];});
      const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workMode,responseLength,creativity,reasoning:usePool||model==='__auto__'?'auto':reasoning,model:usePool?'__pool__':model,usePool,messages:wireMessages,context:includeContext}),signal:controller.signal});
      if(!r.ok){const d=await r.json();throw new Error(d.error||'Keine Antwort erhalten.');}
      if(!r.body)throw new Error('Streaming ist nicht verfügbar.');
      const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',done=false;
      const consume=(line:string)=>{
        if(!line.trim())return;const event=JSON.parse(line);
        if(event.status)setStatus(event.status);
        if(event.selection)updateReply({model:event.selection.model,selectionReason:event.selection.reason});
        if(event.context)updateReply({omittedMessages:event.context.omittedMessages});
        if(event.assigned){updateReply({machine:event.assigned.name,model:event.assigned.model});void refreshPool();}
        if(event.error)throw new Error(event.error);
        if(event.delta){reply+=event.delta;updateReply({});}
        if(event.done){done=true;updateReply({state:'complete',usage:event.usage,truncated:event.finishReason==='length'});}
      };
      try{while(true){const item=await reader.read();if(item.done)break;buffer+=decoder.decode(item.value,{stream:true});let i;while((i=buffer.indexOf('\n'))>=0){consume(buffer.slice(0,i));buffer=buffer.slice(i+1);}}buffer+=decoder.decode();if(buffer.trim())consume(buffer);if(!done)throw new Error('Die Verbindung wurde unterbrochen. Bitte erneut versuchen.');}finally{await reader.cancel().catch(()=>{});}
    }catch(e){
      const message=controller.signal.aborted?'Antwort angehalten.':e instanceof Error?e.message:'Die Antwort konnte nicht geladen werden.';
      setChatError(message);
      if(started){updateReply({state:controller.signal.aborted?'stopped':'error'});setChats(cs=>cs.map(c=>c.id===id?{...c,messages:c.messages.filter(m=>m.role==='user'||m.content)}:c));}
      else if(attachments&&!controller.signal.aborted)throw e;
    }finally{requestInFlight.current=false;setBusy(false);setStatus('');void refreshPool();}
    return started;
  };
  const retry=(index:number)=>{const branch=branchAt(messages,index);void send(branch.message.content,{images:branch.message.images||[],files:branch.message.files||[]},branch.history).catch(e=>notify(e.message));};
  const saveReplyAsNote=(m:Message)=>{const note={id:uid(),title:chat?.title||'Chat-Notiz',body:m.content,updated:Date.now()};const next=[note,...notes];try{storage.write('aevori-notes',next);setNotes(next);notify('Antwort als Notiz gespeichert.');}catch{notify('Die Notiz konnte nicht gespeichert werden. Der Browserspeicher ist voll.');}};
  const addNote=()=>{const n={id:uid(),title:'Neue Notiz',body:'',updated:Date.now()};setNotes(old=>[n,...old]);setNoteId(n.id);go('notes');};
  const addTask=(e:React.FormEvent)=>{e.preventDefault();if(!taskText.trim())return;setTasks(old=>[{id:uid(),text:taskText.trim(),priority,done:false},...old]);setTaskText('');};
  const mainTitle=NAV.find(n=>n.id===view)?.name;
  const health=stats?Math.round(stats.memory.used/stats.memory.total*100):0;
  const composer=<ChatInput value={prompt} onChange={setPrompt} onSend={send} busy={busy} status={status} startedAt={requestStartedAt} onStop={()=>abort.current?.abort()} modelSelect={<ModelSelect models={models} model={model} usePool={usePool} onSelect={id=>{setUsePool(id==='__pool__');if(id!=='__pool__')setModel(id);}} disabled={busy} includeContext={includeContext} onContext={setIncludeContext} ready={pool.nodes.filter(n=>n.online&&n.enabled&&n.models.length).length} openConnections={openConnect} length={responseLength} onLength={setResponseLength} creativity={creativity} onCreativity={setCreativity} reasoning={reasoning} onReasoning={setReasoning} thinking={thinking} allowContext={isOwner} mode={workMode} onMode={setWorkMode}/>} caption={usePool?'Deine Anfrage bleibt in deinem Mac-Pool.':museConnected?'Nachrichten und Anhänge werden bei Meta verarbeitet.':!isOwner?'Deine Anfrage geht an den freigegebenen Arbeitsplatz.':provider.local?'Deine Unterhaltung bleibt auf diesem Mac.':`Nachrichten gehen an ${new URL(provider.baseUrl).hostname}.`}/>;
  const navItems=(ids:View[])=>ids.filter(id=>isOwner||id!=='system').map(id=>{const item=NAV.find(n=>n.id===id)!;return {id,title:item.name,icon:<item.icon size={17}/>,isActive:view===id,badge:id==='tasks'?tasks.filter(t=>!t.done).length:id==='agent'?(agent.state?.messages??[]).filter(m=>m.role==='assistant'&&m.created>(agent.state?.readAt??0)).length:undefined,onSelect:()=>go(id)};});
  const navGroups:SidebarNavGroup[]=[{items:navItems(['chat','agent'])},{label:'Arbeitsplatz',items:navItems(['notes','tasks','team'])},{label:'Verbindungen',defaultOpen:false,items:navItems(['models','muse','system','pool'])}];
  const connectionLabel=usePool?'Mac-Pool':connected?museConnected?'Muse Spark':provider.local?'Lokal verbunden':'Anbieter verbunden':'Nicht verbunden';
  return <AppShell className={`${view==='chat'?'chat-layout':''} ${glass?'glass-sidebar':''} ${busy?'is-thinking':''} ${!isOwner?'team-member':''}`} title={mainTitle||'Chat'} connected={connected} connectionLabel={connectionLabel} onConnection={()=>go('models')} onSettings={()=>{setSettingsTab('profile');go('settings');}} sidebar={<AppSidebar groups={navGroups} chats={visibleChats} activeChat={view==='chat'?chatId:null} busy={busy} profileName={profileName} owner={isOwner} settingsActive={view==='settings'} onNewChat={newChat} onSearch={()=>setSearchOpen(true)} onSettings={()=>{setSettingsTab('profile');go('settings');}} onSelectChat={id=>{setChatId(id);go('chat');setChatError('');}} onDeleteChat={deleteChat}/> }>
      <div className="workspace">
        <section ref={mainContentRef} className={`main-content view-${view}`}>
          {view==='chat'&&<>
            {messages.length>0&&<div className="chat-companion-bar">{museConnected&&!usePool?<MuseAvatar appearance={museAppearance} small active={busy}/>:<Companion appearance={agent.state?.appearance} tone={agent.state?.tone} active={busy} size={42}/>}<div><strong>{museConnected&&!usePool?museAppearance.name:agent.state?.name||'Aeri'}</strong><small>{busy?'Denkt mit dir.':museConnected&&!usePool?'Muse Spark bei Meta':'Dein Gegenüber in AEVORI'}</small></div><button onClick={()=>go('agent')}>Auftrag übergeben<ArrowUpRight size={13}/></button></div>}
            {messages.length?<div ref={conversation} className="conversation" aria-live="polite" onScroll={e=>{const box=e.currentTarget;followReply.current=box.scrollHeight-box.scrollTop-box.clientHeight<80;}}>{messages.map((m,i)=><ChatMessage key={i} avatar={m.model?.startsWith('muse-spark-')?<MuseAvatar appearance={museAppearance} small active={busy&&i===messages.length-1}/>:<Companion appearance={agent.state?.appearance} tone={agent.state?.tone} active={busy&&i===messages.length-1} size={30}/>} message={m} active={busy&&i===messages.length-1} busy={busy} status={status} onCopy={()=>void navigator.clipboard.writeText(m.content).then(()=>notify('Antwort kopiert.')).catch(()=>notify('Kopieren ist nicht verfügbar.'))} onRetry={()=>retry(i)} onEdit={()=>setEditing({index:i,text:m.content})} onNote={()=>saveReplyAsNote(m)} onTask={()=>setTaskDraft(m.content)}/>)}{chatError&&<div className="error-banner" role="alert">{chatError}{!busy&&messages.some(m=>m.role==='user')&&<button className="text-button" onClick={()=>retry(messages.length-1)}>Erneut versuchen</button>}</div>}<div ref={end}/></div>:<div className="welcome"><div className="welcome-aevori">{museConnected&&!usePool?<MuseAvatar appearance={museAppearance}/>:agent.state?.characterConfigured?<Companion appearance={agent.state.appearance} size={78}/>:<BrandLogo symbol/>}</div><h1>Womit möchtest du loslegen?</h1><span>Schreiben, gestalten und entwickeln.<br/>{museConnected&&!usePool?'Mit Muse Spark von Meta.':'Mit KI auf deinem Mac.'}</span><div className="suggestions"><button onClick={()=>{setWorkMode('writing');setPrompt('Hilf mir, einen klaren Text zu schreiben. ');}}><Activity size={15}/>Text verfeinern<ArrowUpRight size={13}/></button><button onClick={()=>{setWorkMode('design');setPrompt('Hilf mir, ein übersichtliches Interface zu gestalten. ');}}><HardDrive size={15}/>Design durchdenken<ArrowUpRight size={13}/></button><button onClick={()=>{setWorkMode('code');setPrompt('Hilf mir, eine kleine App zu entwickeln. ');}}><Sparkles size={15}/>Code entwickeln<ArrowUpRight size={13}/></button></div></div>}
            {composer}
          </>}
          {view==='agent'&&<AgentWorkspace agent={agent} onOpen={go} onChat={newChat} initialTab={agentSection}/>}
          {view==='settings'&&<SettingsPage tab={settingsTab} onTab={setSettingsTab} name={profileName} owner={isOwner} onName={name=>{setProfileName(name);setProfileConfigured(true);notify('Dein Name wurde gespeichert.');}} agent={agent} theme={theme} onTheme={setTheme} glass={glass} onGlass={setGlass} motion={motion} onMotion={setMotion} connected={connected} providerName={provider.type==='ollama'?'Ollama':provider.brand==='meta-muse'?'Meta Muse':'Kompatible API'} modelName={modelLabel(model)} nodeCount={pool.nodes.length} contentCount={{chats:visibleChats.length,notes:notes.length,tasks:tasks.length}} deletedChats={chats.filter(c=>Boolean(c.deletedAt))} onRestore={restoreChat} onSetup={()=>setSetupOpen(true)} onOpen={go} onOpenAgent={section=>{go('agent');setAgentSection(section);}} notify={notify} onExport={()=>{const blob=new Blob([JSON.stringify({version:1,chats,notes,tasks},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aevori-inhalte.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Deine Inhalte wurden exportiert.');}}/>}
          {view==='muse'&&<MuseWorkspace appearance={museAppearance} onAppearance={setMuseAppearance} storage={storage} connected={museConnected} busy={busy} status={status} owner={isOwner} cliInstalled={museCliInstalled} model={modelLabel(model)} tasks={tasks} onTask={id=>setTasks(ts=>ts.map(t=>t.id===id?{...t,done:true}:t))} onOpen={go} onStart={startMuse} onConnect={openMuseConnect}/>}
          {view==='pool'&&<PoolPanel readOnly={!isOwner} pool={pool} refresh={refreshPool} startChat={()=>{setUsePool(true);newChat();}}/>}
          {view==='team'&&<TeamPanel session={{...session,name:profileName,profileConfigured}}/>}
          {view==='system'&&<><div className="page-heading"><span className="eyebrow">Dieser Mac</span><h1>Alles läuft zusammen.</h1><p>Live-Messwerte von deinem Gerät. Alle 3 Sekunden aktualisiert.</p><button className="text-button" onClick={()=>go('pool')}><Network size={16}/>Weitere Macs verbinden<ArrowUpRight size={14}/></button></div>{systemError?<div className="error-banner">{systemError}</div>:stats?<><div className="system-summary"><div className="machine-art"><MacImage name={stats.hardware.name}/></div><div><span className="connected-pill"><span className="status-dot online"/>Verbunden</span><h2>{stats.hardware.name}</h2><p>{stats.hardware.chip} · {stats.hardware.cores} Kerne</p><p>macOS {stats.hardware.os} · {bytes(stats.memory.total)} Arbeitsspeicher</p><span className="subtle">Seit {Math.floor(stats.uptime/3600)} {Math.floor(stats.uptime/3600)===1?'Stunde':'Stunden'} eingeschaltet</span></div></div><div className="metrics-grid"><div><Cpu size={19}/><label>CPU-Auslastung</label><strong>{stats.cpu}<small>%</small></strong><LiveChart values={history}/></div><div><MemoryStick size={19}/><label>Arbeitsspeicher</label><strong>{bytes(stats.memory.used)}</strong><p>von {bytes(stats.memory.total)} · inkl. Cache</p><div className="usage-bar"><i style={{width:health+'%'}}/></div></div><div><HardDrive size={19}/><label>Freier Speicher</label><strong>{stats.disk?bytes(stats.disk.free):'Nicht verfügbar'}</strong><p>{stats.disk?`von ${bytes(stats.disk.total)}`:'Laufwerk konnte nicht gelesen werden.'}</p><div className="usage-bar"><i style={{width:stats.disk?100*stats.disk.free/stats.disk.total+'%':'0'}}/></div></div></div><div className="process-header"><h2>Laufende Prozesse</h2><span>Nach CPU sortiert · nur lesen</span></div><div className="process-table"><div className="process-row table-label"><span>Prozess</span><span>CPU</span><span>Arbeitsspeicher</span></div>{stats.processes.map(p=><div className="process-row" key={p.pid}><span><ProcessIcon icon={p.icon}/>{p.name}</span><span>{p.cpu.toFixed(1)} %</span><span>{p.memory>GB?bytes(p.memory):`${Math.round(p.memory/1024**2)} MB`}</span></div>)}</div><p className="fine-print">Ein Prozess kann mehrere CPU-Kerne nutzen und dadurch über 100 % liegen. Aevori beendet keine Prozesse automatisch.</p></>:<div className="empty-state"><Mark busy/><p>Dein Mac wird verbunden …</p></div>}</>}
          {view==='models'&&<><div className="page-heading with-action"><div><span className="eyebrow">Verbindungen</span><h1>Intelligenz. Nach deiner Wahl.</h1><p>Qwen, Muse Spark oder dein eigener Anbieter. Ein gemeinsamer Arbeitsplatz.</p></div><button className="primary" disabled={busy} onClick={openConnect}><Plus size={16}/>Verbinden</button></div><div className="provider-canvas"><ModelEcosystem/><div className="connection-row"><div className="connection-icon"><Network size={21}/></div><div><h3>{provider.type==='ollama'?'Ollama':provider.brand==='meta-muse'?'Meta Muse':'Kompatible API'}</h3><p>{provider.baseUrl}</p></div><span className={`connected-pill ${!connected?'offline':''}`}><span className={`status-dot ${connected?'online':''}`}/>{connected?'Verbunden':'Nicht erreichbar'}</span><button className="icon-button" aria-label="Modelle aktualisieren" disabled={refreshing||busy} onClick={()=>void refreshModels()}><RefreshCw size={17} className={refreshing?'spin':''}/></button></div></div>{connectionError&&<div className="error-banner">{connectionError}<button className="text-button" onClick={openConnect}>Verbindung bearbeiten</button></div>}<div className="muse-provider-card"><img src="/ai-logos/meta-color.svg" alt=""/><div><h3>Muse Spark von Meta</h3><p>Gemeinsam denken, schreiben und Bilder verstehen.</p></div><button className="secondary" onClick={()=>go('muse')}>Muse entdecken<ChevronRight size={15}/></button></div><ModelInstall chatBusy={busy} available={isOwner&&provider.type==='ollama'&&provider.local&&connected} installed={provider.type==='ollama'&&provider.local?models:[]} freeBytes={stats?.disk?.free} onComplete={()=>void refreshModels()} onSelect={id=>{setModel(id);setUsePool(false);newChat();}}/><div className="section-heading models-heading"><h2>Verfügbare Modelle</h2><span>{models.length} gefunden</span></div><div className="model-list">{models.map(m=><button key={m.id} disabled={busy} className={`model-card ${m.id===model?'selected':''}`} onClick={()=>{setModel(m.id);setUsePool(false);notify(`${m.id} ausgewählt.`);}}><div className="model-symbol"><ModelLogo model={m.id} size={27}/></div><div><h3>{modelLabel(m.id)}</h3><p>{[modelInfo(m.id)?.category,m.parameters,m.quantization,m.size?bytes(m.size):null,provider.local?'Auf deinem Mac':'Beim Anbieter'].filter(Boolean).join(' · ')}</p></div>{m.id===model?<span className="selected-model"><Check size={15}/>Aktiv</span>:<ChevronRight size={16}/>}</button>)}</div>{!models.length&&<div className="empty-inline"><p>Noch kein Modell verfügbar.</p><span>Starte Ollama mit einem installierten Modell oder verbinde einen anderen Anbieter.</span></div>}<div className="model-footnote"><ShieldCheck size={18}/><p>Lokale Modelle laufen auf deinem Gerät. Bei anderen Anbietern gehen nur deine Chatnachrichten und der von dir aktivierte Mac-Kontext an die eingetragene Adresse. API-Schlüssel bleiben im Arbeitsspeicher des lokalen Dienstes.</p></div></>}
          {view==='notes'&&<NotesPanel notes={notes} noteId={noteId} onSelect={setNoteId} onAdd={addNote} onChange={updated=>setNotes(ns=>ns.map(n=>n.id===updated.id?updated:n))} onDelete={id=>{setNotes(ns=>ns.filter(n=>n.id!==id));if(noteId===id)setNoteId(null);}}/>}
          {view==='tasks'&&<><div className="page-heading"><span className="eyebrow">Aufgaben</span><h1>Ein Gedanke weniger.</h1><p>{tasks.length?`${tasks.filter(t=>!t.done).length} offen. ${tasks.filter(t=>t.done).length} erledigt.`:'Was möchtest du heute schaffen?'}</p></div><form className="task-form" onSubmit={addTask}><Plus size={19}/><input aria-label="Neue Aufgabe" placeholder="Eine Aufgabe hinzufügen …" maxLength={250} value={taskText} onChange={e=>setTaskText(e.target.value)}/><AevoriSelect label="Priorität" value={priority} onValueChange={value=>setPriority(value as Task["priority"])} options={[{value:"low",label:"Niedrig"},{value:"medium",label:"Mittel"},{value:"high",label:"Hoch"}]}/><button className="primary" disabled={!taskText.trim()}>Hinzufügen</button></form><div className="task-list">{tasks.map(t=><div className={`task ${t.done?'done':''}`} key={t.id}><button className="task-check" aria-label={t.done?'Aufgabe wieder öffnen':'Aufgabe erledigen'} onClick={()=>setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done&&<Check size={14}/>}</button><span>{t.text}</span><span className={`priority ${t.priority}`}><i/>{t.priority==='high'?'Hoch':t.priority==='low'?'Niedrig':'Mittel'}</span><button className="icon-button" aria-label="Aufgabe löschen" onClick={()=>setTasks(ts=>ts.filter(x=>x.id!==t.id))}><X size={14}/></button></div>)}</div>{!tasks.length&&<div className="empty-state"><CheckCircle2 size={38}/><h2>Alles noch offen. Im guten Sinne.</h2><p>Halte oben deine erste Aufgabe fest.</p></div>}</>}
        </section>

      </div><nav className="mobile-dock" aria-label="Schnellnavigation">{([{id:'chat',name:'Chat',icon:MessageCircle},{id:'agent',name:'Agent',icon:Activity},{id:'tasks',name:'Aufgaben',icon:CheckCheck},{id:'models',name:'Verbinden',icon:Link2}] as const).map(n=><button key={n.id} aria-current={view===n.id?'page':undefined} onClick={()=>go(n.id)}><n.icon size={19}/>{n.name}</button>)}</nav><footer className="statusbar"><span><span className={`status-dot ${!systemError&&stats?'online':''}`}/>{stats&&!systemError?'Mit diesem Mac verbunden':'Verbindung wird hergestellt'}</span><span>Aevori Preview <span className="footer-separator">/</span> Intelligence, locally.</span></footer>
    <Modal open={connectOpen} onOpenChange={b=>{if(!connecting){setConnectOpen(b);if(!b){setForm(f=>({...f,apiKey:''}));museDraft.current=null;}}}} title="Eine neue Verbindung." description="Gib deiner KI einen Platz in Aevori."><div className="connection-stack"><div/><div/><div><Mark small/><span>Dein Modell. Dein Arbeitsplatz.</span><ShieldCheck size={16}/></div></div><form onSubmit={connect} className="connection-form"><label>Anbieter<AevoriSelect label="Anbieter" value={form.baseUrl==='https://api.meta.ai/v1'?'muse':form.type} onValueChange={type=>setForm({type:type==='muse'?'compatible':type,baseUrl:type==='ollama'?'http://127.0.0.1:11434':type==='muse'?'https://api.meta.ai/v1':'http://127.0.0.1:1234/v1',apiKey:''})} options={[{value:'muse',label:'Meta Muse · Cloud'},{value:"ollama",label:"Ollama · lokale Modelle"},{value:"compatible",label:"OpenAI-kompatible API · z. B. LM Studio"}]}/></label>{form.baseUrl==='https://api.meta.ai/v1'&&<div className="muse-form-notice">Muse Spark läuft bei Meta. Gesendete Nachrichten und Anhänge verlassen deinen Mac. API-Nutzung kann Kosten verursachen; AEVORI verwendet den Standard-Tarif.<a href="https://dev.meta.ai/" target="_blank" rel="noreferrer">Meta Developer Dashboard öffnen ↗</a>Dein Muse-App-Login und ein API-Schlüssel sind unterschiedliche Zugänge.</div>}<label>Server-Adresse<input readOnly={form.baseUrl==='https://api.meta.ai/v1'} required type="url" value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})}/></label><label>API-Schlüssel <span>optional bei lokalen Anbietern</span><input required={form.baseUrl==='https://api.meta.ai/v1'} type="password" value={form.apiKey} autoComplete="off" onChange={e=>setForm({...form,apiKey:e.target.value})} placeholder="Nur für diese Sitzung"/></label><p className="fine-print">Die Verbindung wird vor dem Speichern geprüft. Ein anderer Anbieter ersetzt die aktive Verbindung und öffnet einen neuen Chat. Bestehende Verläufe bleiben erhalten. Schlüssel werden nicht dauerhaft gespeichert.</p>{formError&&<p className="error-banner" role="alert">{formError}</p>}<button className="primary wide" disabled={connecting}>{connecting?<RefreshCw className="spin" size={16}/>:<Link2 size={16}/>} {connecting?'Verbindung prüfen …':'Prüfen und verbinden'}</button></form></Modal>
    <Modal open={searchOpen} onOpenChange={setSearchOpen} title="Wohin soll es gehen?" className="search-dialog"><div className="command-search"><Search size={18}/><input autoFocus aria-label="Bereich suchen" placeholder="Bereich suchen …" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>esc</kbd></div><div className="command-results">{NAV.filter(n=>(isOwner||n.id!=='system')&&n.name.toLowerCase().includes(query.toLowerCase())).map(n=><button key={n.id} onClick={()=>go(n.id)}><n.icon size={18}/>{n.name}<ChevronRight size={15}/></button>)}</div></Modal>
    <Modal open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}} title="Nachricht bearbeiten" description="Die Antwort wird in einem neuen Chat erzeugt. Dein bisheriger Verlauf bleibt erhalten.">
      <form className="reply-edit-form" onSubmit={e=>{e.preventDefault();if(!editing)return;const branch=branchAt(messages,editing.index),text=editing.text;setEditing(null);void send(text,{images:branch.message.images||[],files:branch.message.files||[]},branch.history).catch(e=>notify(e.message));}}><textarea aria-label="Nachricht bearbeiten" value={editing?.text||''} onChange={e=>setEditing(old=>old?{...old,text:e.target.value}:null)} rows={7} maxLength={20000}/><button className="primary" disabled={!editing?.text.trim()||busy}>Als neuen Verlauf senden</button></form>
    </Modal>
    <Modal open={taskDraft!==null} onOpenChange={open=>{if(!open)setTaskDraft(null);}} title="Aufgabe erstellen" description="Bearbeite den Vorschlag, bevor du ihn zu deinen Aufgaben hinzufügst.">
      <form className="reply-edit-form" onSubmit={e=>{e.preventDefault();if(!taskDraft?.trim())return;const next=[{id:uid(),text:taskDraft.trim(),priority:'medium' as const,done:false},...tasks];try{storage.write('aevori-tasks',next);setTasks(next);setTaskDraft(null);notify('Aufgabe gespeichert.');}catch{notify('Aufgabe konnte nicht gespeichert werden.');}}}><textarea aria-label="Aufgabentext" value={taskDraft||''} onChange={e=>setTaskDraft(e.target.value)} rows={7} maxLength={10000}/><button className="primary" disabled={!taskDraft?.trim()}>Aufgabe speichern</button></form>
    </Modal>
    {setupOpen&&<ProfileSetup name={profileName} theme={theme} onTheme={setTheme} ready={connected&&models.length>0} status={connected&&models.length?`${models.length} ${models.length===1?'Modell bereit':'Modelle bereit'} · ${!isOwner?'Über deinen Gastgeber':provider.local?'Auf deinem Mac':'Bei deinem Anbieter'}`:'Du kannst gleich ein Modell verbinden.'} canClose={profileConfigured} onClose={()=>setSetupOpen(false)} onComplete={(name,destination)=>{setProfileName(name);setProfileConfigured(true);setSetupOpen(false);go(destination);notify(`Willkommen, ${name}.`);}}/>}
    {toast&&<div className="toast" role="status"><CheckCircle2 size={16}/>{toast}{undoChat&&<button onClick={()=>restoreChat(undoChat)}>Rückgängig</button>}</div>}
  </AppShell>;
}
