import {useState} from 'react';
import {Monitor,Plus,Network,RefreshCw,Copy,Trash2,ShieldCheck,ChevronRight,X,Check} from './MotionIcon';
import MacImage from './components/MacImage';
import ModelLogo from './components/ModelLogo';
export type PoolNode={id:string;name:string;enabled:boolean;online:boolean;models:{id:string}[];active:number;error:string;hardware?:{name:string;chip:string;cores:number};memory?:{total:number;used:number};cpu?:number};
export type PoolState={nodes:PoolNode[];sharing:boolean};
export async function poolRequest(path:string,data:unknown){const r=await fetch('/api/pool/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw new Error(value.error||'Verbindung fehlgeschlagen.');return value;}
export default function PoolPanel({pool,refresh,startChat,readOnly=false}:{readOnly?:boolean;pool:PoolState;refresh:()=>Promise<void>;startChat:()=>void}){
 const [adding,setAdding]=useState(false),[sharing,setSharing]=useState(false),[token,setToken]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const [form,setForm]=useState({name:'',baseUrl:'http://127.0.0.1:5191',token:''});
 const ready=pool.nodes.filter(n=>n.enabled&&n.online&&n.models.length),active=pool.nodes.reduce((sum,n)=>sum+n.active,0);
 const act=async(fn:()=>Promise<unknown>)=>{setPending(true);setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:'Verbindung fehlgeschlagen.');}finally{setPending(false);}};
 return <>
 <div className="page-heading with-action"><div><span className="eyebrow">Gemeinsam verbunden</span><h1>Mehr Macs. Ein Aevori.</h1><p>Deine KI-Anfragen finden den nächsten freien Mac.</p></div><button className="primary" disabled={readOnly} onClick={()=>setAdding(!adding)}><Plus size={16}/>Mac verbinden</button></div>
 <section className="pool-hub"><div className="pool-hub-copy"><span className="connected-pill"><span className={`status-dot ${ready.length?'online':''}`}/>{ready.length} {ready.length===1?'Mac bereit':'Macs bereit'}</span><h2>Ein Team.<br/>Mehr Möglichkeiten.</h2><p>Verbinde deine Macs. Aevori verteilt jede neue Anfrage auf einen freien Rechner mit dem passenden Modell.</p><div className="pool-hub-numbers"><div><strong>{pool.nodes.length.toString().padStart(2,'0')}</strong><span>Verbundene Macs</span></div><div><strong>{active.toString().padStart(2,'0')}</strong><span>Aktive Anfragen</span></div><div><strong>{new Set(pool.nodes.filter(n=>n.online&&n.enabled).flatMap(n=>n.models.map(m=>m.id))).size.toString().padStart(2,'0')}</strong><span>Verfügbare Modelle</span></div></div><button className="primary" onClick={startChat} disabled={!ready.length}>Mit dem Pool chatten<ChevronRight size={16}/></button></div><div className="pool-hardware-scene"><div className="hardware-halo"/><MacImage name={pool.nodes[0]?.hardware?.name||'Mac Studio'} className="pool-primary-mac"/><span className="pool-scene-label"><span className={`status-dot ${ready.length?'online':''}`}/>{pool.nodes[0]?.name||'Dein Mac'}<small>{pool.nodes[0]?.hardware?.chip||'Bereit zum Verbinden'}</small></span><div className="pool-link-line"/><div className="pool-scene-peers">{pool.nodes.slice(1,4).map(n=><div key={n.id}><MacImage name={n.hardware?.name||n.name}/><span>{n.name}</span></div>)}<button disabled={readOnly} onClick={()=>setAdding(true)}><Plus size={19}/><span>Mac hinzufügen</span></button></div></div><div className="pool-hub-footer"><span><ShieldCheck size={14}/>Deine Rechner. Deine Modelle. Dein privater Pool.</span><button className="text-button" onClick={()=>void act(refresh)} disabled={pending}><RefreshCw size={14}/>Aktualisieren</button></div></section>
 {error&&<p className="error-banner" role="alert">{error}</p>}
 {adding&&<section className="pool-setup"><div className="section-heading"><h2>Einen Mac in deinen Aevori holen.</h2><button className="icon-button" aria-label="Verbindung schließen" onClick={()=>setAdding(false)}><X size={18}/></button></div><div className="setup-columns"><ol className="setup-steps"><li><strong>Aevori auf dem anderen Mac starten.</strong><span>Ollama starten und dort mindestens ein Modell installieren.</span></li><li><strong>Diesen Mac freigeben.</strong><span>Dort unter „Mac-Pool“ den Verbindungsschlüssel erstellen.</span></li><li><strong>Sichere Verbindung öffnen.</strong><span>Auf diesem Mac einen SSH-Tunnel starten. Ersetze Benutzer und Mac-Adresse durch deine eigenen Angaben.</span><code>ssh -N -L 5191:127.0.0.1:5190 BENUTZER@MAC.local</code><span>Alternativ kannst du eine bereits eingerichtete HTTPS-Adresse verwenden.</span></li></ol><form className="connection-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await poolRequest('add',form);setForm({name:'',baseUrl:'http://127.0.0.1:5191',token:''});setAdding(false);});}}><label>Name des Macs<input required maxLength={60} placeholder="Mac Studio im Büro" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Aevori-Adresse<input required type="url" value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})}/></label><label>Verbindungsschlüssel<input required type="password" autoComplete="off" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/></label><button className="primary wide" disabled={pending}>{pending?'Verbindung prüfen …':'Prüfen und hinzufügen'}</button><p className="fine-print">Verbindungen gelten für diese Sitzung. Jeder weitere Tunnel benötigt einen eigenen lokalen Port, z. B. 5192.</p></form></div></section>}
 <div className="section-heading models-heading"><h2>Deine Rechner</h2><span>{pool.nodes.length} im Pool</span></div><div className="pool-machine-list">{pool.nodes.map(n=><article key={n.id} className="pool-machine"><div className="pool-machine-icon"><MacImage name={n.hardware?.name||n.name}/></div><div className="pool-machine-copy"><h3>{n.name}{n.id==='local'&&<small>Dieser Mac</small>}</h3><p>{n.hardware?.chip||'Aevori-Mac'}{n.memory?` · ${Math.round(n.memory.total/1024**3)} GB RAM`:''}</p><div className="pool-models">{n.models.map(m=><span key={m.id}><ModelLogo model={m.id} size={14}/>{m.id.replace(':latest','')}</span>)}</div>{n.error&&<p className="small-error">{n.error}</p>}</div><div className="pool-machine-state"><span className={`status-dot ${n.online&&n.enabled?'online':''}`}/>{!n.enabled?'Pausiert':!n.online?'Offline':n.active?`${n.active} aktiv`:'Bereit'}</div><button role="switch" aria-label={`${n.name} im Pool nutzen`} aria-checked={n.enabled} disabled={pending||readOnly} className={`toggle ${n.enabled?'on':''}`} onClick={()=>void act(()=>poolRequest('update',{id:n.id,enabled:!n.enabled}))}><i/></button>{!readOnly&&n.id!=='local'&&<button className="icon-button" aria-label={`${n.name} entfernen`} disabled={pending||n.active>0} onClick={()=>void act(()=>poolRequest('update',{id:n.id,remove:true}))}><Trash2 size={16}/></button>}</article>)}</div>
 {!readOnly&&<section className="share-machine"><div><ShieldCheck size={22}/><div><h3>Diesen Mac für deinen Pool freigeben</h3><p>Andere Aevori-Macs können ihn mit einem Sitzungsschlüssel nutzen.</p></div></div><button className="secondary" onClick={()=>setSharing(!sharing)}>{sharing?'Schließen':pool.sharing?'Freigabe verwalten':'Freigabe einrichten'}<ChevronRight size={15}/></button></section>}
 {sharing&&<div className="pool-setup sharing-details"><p>Der Schlüssel erlaubt KI-Anfragen und das Lesen der Geräteauslastung. Er gilt bis zum Stoppen der Freigabe oder zum Neustart von Aevori.</p>{token&&<div className="share-token"><input aria-label="Sitzungsschlüssel" type="password" readOnly value={token}/><button className="secondary" onClick={()=>void navigator.clipboard.writeText(token).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2500);}).catch(()=>setError('Der Schlüssel konnte nicht kopiert werden.'))}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Kopiert':'Kopieren'}</button></div>}<div className="row"><button className="primary" disabled={pending} onClick={()=>void act(async()=>{const d=await poolRequest('share',{enable:true});setToken(d.token);})}>{pool.sharing?'Neuen Schlüssel erstellen':'Freigeben und Schlüssel erstellen'}</button>{pool.sharing&&<button className="secondary" disabled={pending} onClick={()=>void act(async()=>{await poolRequest('share',{enable:false});setToken('');})}>Freigabe stoppen</button>}</div></div>}
 <p className="fine-print pool-explainer">Aevori verteilt vollständige Anfragen auf aktive Macs mit passenden Modellen. Der Arbeitsspeicher bleibt pro Gerät getrennt. Fällt ein Mac vor Beginn der Antwort aus, versucht Aevori den nächsten. Deine Unterhaltung wird an den ausgewählten Mac gesendet.</p>
 </>;
}
